---
# Tasks to build offline dhcpd.conf file

- name: 'Execute DHCP configuration role'
  import_role:
    name: arista.cvp.dhcp_configuration
  vars:
    mode: offline
    output_dir: '{{ root_dir }}/intended/configs/'
  delegate_to: localhost
  run_once: true
