---
# Tasks to build online dhcpd.conf to specified server

- name: 'Execute DHCP configuration role'
  import_role:
    name: arista.cvp.dhcp_configuration
  vars:
    mode: online
    output_dir: '{{ root_dir }}/intended/configs/'
