---
- name: Remove output folders
  hosts: all
  gather_facts: false
  connection: local
  vars:
    inventory_dir: '{{playbook_dir}}/inventory'
    root_dir: '{{playbook_dir}}/inventory'
  tasks:
    - name: delete local folders
      delegate_to: 127.0.0.1
      run_once: true
      file:
        path: "{{root_dir}}/{{ item }}"
        state: absent
      with_items:
        - documentation
        - intended
        - config_backup
        - reports
        - snapshots
        - upgrade_1.0_to_1.1/group_vars/DC1_TENANTS_NETWORKS.yml