### Routing - OSPF ###
router_ospf:
  process_ids:
    100:
      passive_interface_default: true
      router_id: 192.168.255.3
      no_passive_interfaces:
        - Ethernet1
        - Ethernet2
        - Vlan4093
      bfd_enable: true
      max_lsa: 12000
      default_information_originate:
      redistribute:
        static:
        connected:
    200:
      vrf: ospf_zone
      passive_interface_default: false
      router_id: 192.168.254.1
      log_adjacency_changes_detail: true
      bfd_enable: false
      max_lsa: 5
      default_information_originate:
        always: true
      redistribute:
        static:
          route_map: rm-ospf-static
        connected:
          route_map: rm-ospf-connected
