name: Test Installation
on:
  pull_request:
    branches:
      - 'releases/v**'
  schedule:
    - cron:  '0 6 * * *'
jobs:
  'setup':
    name: 'One liner installation'
    runs-on: ubuntu-18.04
    container: avdteam/base:3.6-v1.0
    steps:
      - uses: actions/checkout@master
      - name: Execute one-liner installation
        run: |
          cd /tmp/
          curl -fs https://get.avd.sh | sh
      - name: Run Makefile commands
        run: |
          cd /tmp/arista-ansible/
          cat Makefile
          make
